sub asy {return system("asy \"$_[0]\"");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");

$pdf_mode = 1;
$out_dir = "./build/";

# forward these args to all engines
# set_tex_cmds('%O -shell-escape -interaction=nonstopmode %S');
# batchmode should be quieter
set_tex_cmds('%O -shell-escape -interaction=batchmode %S');
