#! /bin/bash

DISPNUM=${DISPLAY:1}

[ "$XMOBAR_PIPE_LOCATION" == "" ] &&
  XMOBAR_PIPE_LOCATION="$HOME/.local/share/xmobar"

[ ! -d "$XMOBAR_PIPE_LOCATION" ] && mkdir -p "$XMOBAR_PIPE_LOCATION"

XMOBAR_INPUT_PIPE="$XMOBAR_PIPE_LOCATION/xmobar.pipe.$DISPNUM"
XMOBAR_NOTIFICATION_PIPE="$XMOBAR_PIPE_LOCATION/notifications.pipe.$DISPNUM"

export XMOBAR_NOTIFICATION_PIPE
export XMOBAR_INPUT_PIPE
export BROWSER=xdg-open

if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
 done
fi

# startup configuration script for Xorg

# read .Xresrouces
xrdb -merge ~/.Xresources

# set up left pointer as cursor
xsetroot -cursor_name left_ptr

# set shell level to 0
export SHLVL=-3

# set wallpaper
# xloadimage -onroot -fullscreen ~/wallpapers/archanime.png
[[ -f $HOME/.set-wallpaper ]] && $HOME/.set-wallpaper

# set key repeat rates
xset r rate 250 60

# start compton for compositing
compton --no-fading-openclose &

xset -dpms
xset s off

# trayer --edge top --align right --SetDockType true --SetPartialStrut true \
#     --expand true --width 10 --transparent true --height 10 &

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export RXVT_SOCKET="$HOME/.urxvt/urxvtd.$DISPNUM"

[ -e "$XMOBAR_INPUT_PIPE" ] || mkfifo "$XMOBAR_INPUT_PIPE"
[ -e "$XMOBAR_NOTIFICATION_PIPE" ] || mkfifo "$XMOBAR_NOTIFICATION_PIPE"

# start useful services
xmobar $HOME/.xmonad/xmobarrc &
stalonetray --config $HOME/.xmonad/stalonetrayrc &
nm-applet &
ibus-daemon -rx &
urxvtd -f -o

# start xmonad
exec xmonad

rm "$XMOBAR_INPUT_PIPE"
rm "$XMOBAR_NOTIFICATION_PIPE"
